apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-10-16T12:15:47Z"
  generation: 1
  labels:
    run: webapp-v1
  name: webapp-v1
  namespace: default
  resourceVersion: "59718"
  selfLink: /apis/apps/v1/namespaces/default/deployments/webapp-v1
  uid: 1aa33d3a-e492-43be-b2f7-279cae869ce2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: webapp-v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: webapp-v1
    spec:
      containers:
      - image: arig23498/webapp
        imagePullPolicy: Always
        name: webapp-v1
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-10-16T12:15:58Z"
    lastUpdateTime: "2019-10-16T12:15:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-10-16T12:15:47Z"
    lastUpdateTime: "2019-10-16T12:15:58Z"
    message: ReplicaSet "webapp-v1-56cc67bb49" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1