apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-16T12:17:15Z"
  labels:
    run: webapp-v1
  name: webapp-v1
  namespace: default
  resourceVersion: "59826"
  selfLink: /api/v1/namespaces/default/services/webapp-v1
  uid: 467fd1e8-c63b-46de-9a28-8d6f27cdb049
spec:
  clusterIP: 10.97.35.170
  externalIPs:
  - 104.211.230.185
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32607
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    run: webapp-v1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}